[package]
name = "wordmash"
description = "Implementations of arithmetic operations for strings as numbers in a specialised alphabet"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.24.1"
