[package]
name = "wordmash"
description = "Implementations of arithmetic operations for strings as base 36 numbers"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.24.1"
